stages:
- name: build and publish docker
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: garelp/ubuntu-ssh:test
      pushRemote: true
      registry: index.docker.io
  - applyYamlConfig:
      path: ./deploy-pod.yaml
- name: Expose services
  steps:
  - applyYamlConfig:
      path: ./deploy-lb.yaml
timeout: 60
notification:
  recipients:
  - recipient: garelp@toplite.org
    notifier: c-jgz5f:n-h7mk9
  condition:
  - Success
  - Changed
  - Failed
