stages:
- name: build and publish docker
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: garelp/ubuntu-ssh:test
      pushRemote: true
      registry: index.docker.io
timeout: 60
notification: {}
