apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-ssh
spec:
  selector:
    matchLabels:
      run: my-ssh
  replicas: 1
  template:
    metadata:
      labels:
        run: my-ssh
    spec:
      containers:
      - name: my-ssh
        image: garelp/ubuntu-ssh:1.8
        ports:
        - containerPort: 2222
